# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\action_system\action_system\widgets\ui\center_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Center_Menu(object):
    def setupUi(self, Center_Menu):
        Center_Menu.setObjectName("Center_Menu")
        Center_Menu.resize(1920, 1080)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Center_Menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Center_Menu)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background/figs/background/规范.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.base_frame = QtWidgets.QFrame(Center_Menu)
        self.base_frame.setStyleSheet("QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,stop:0 rgb(0, 170, 255), stop:1 rgba(0, 0, 0, 255));}")
        self.base_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.base_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.btn_nextWindow = QtWidgets.QToolButton(self.base_frame)
        self.btn_nextWindow.setMinimumSize(QtCore.QSize(300, 300))
        self.btn_nextWindow.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_nextWindow.setFont(font)
        self.btn_nextWindow.setAutoFillBackground(False)
        self.btn_nextWindow.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"    border-style: flat;\n"
"    background: transparent;\n"
"}\n"
"QToolButton:hover{background-color: rgb(0, 170, 255)}\n"
"QToolButton:pressed{background-color: rgb(0, 85, 255)}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/figs/icon/跟随训练.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nextWindow.setIcon(icon)
        self.btn_nextWindow.setIconSize(QtCore.QSize(100, 100))
        self.btn_nextWindow.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_nextWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_nextWindow.setObjectName("btn_nextWindow")
        self.verticalLayout_4.addWidget(self.btn_nextWindow)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.btn_grade = QtWidgets.QToolButton(self.base_frame)
        self.btn_grade.setMinimumSize(QtCore.QSize(300, 300))
        self.btn_grade.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_grade.setFont(font)
        self.btn_grade.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"    border-style: flat;\n"
"    background: transparent;\n"
"}\n"
"QToolButton:hover{background-color: rgb(0, 170, 255)}\n"
"QToolButton:pressed{background-color: rgb(0, 85, 255)}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/figs/icon/118评估.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_grade.setIcon(icon1)
        self.btn_grade.setIconSize(QtCore.QSize(100, 100))
        self.btn_grade.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_grade.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_grade.setObjectName("btn_grade")
        self.verticalLayout.addWidget(self.btn_grade)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(401, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_back = QtWidgets.QPushButton(self.base_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setMinimumSize(QtCore.QSize(400, 100))
        self.btn_back.setMaximumSize(QtCore.QSize(800, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgba(50, 50, 50,0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{padding-bottom:8px}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/figs/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon2)
        self.btn_back.setIconSize(QtCore.QSize(45, 45))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.base_frame)

        self.retranslateUi(Center_Menu)
        QtCore.QMetaObject.connectSlotsByName(Center_Menu)

    def retranslateUi(self, Center_Menu):
        _translate = QtCore.QCoreApplication.translate
        Center_Menu.setWindowTitle(_translate("Center_Menu", "Form"))
        self.btn_nextWindow.setText(_translate("Center_Menu", "动作规范训练课程选择"))
        self.btn_grade.setText(_translate("Center_Menu", "成绩查询"))
        self.btn_back.setText(_translate("Center_Menu", "返回训练选择界面"))
import res_rc
