# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\action_system\action_system\widgets\ui\std_train_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Std_Train_Select(object):
    def setupUi(self, Std_Train_Select):
        Std_Train_Select.setObjectName("Std_Train_Select")
        Std_Train_Select.resize(1920, 1080)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Std_Train_Select)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(Std_Train_Select)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background/figs/background/规范.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.base_frame = QtWidgets.QFrame(Std_Train_Select)
        self.base_frame.setStyleSheet("QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,stop:0 rgb(0, 170, 255), stop:1 rgba(0, 0, 0, 255));}")
        self.base_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.base_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.btn_ac_analysis = QtWidgets.QToolButton(self.base_frame)
        self.btn_ac_analysis.setMinimumSize(QtCore.QSize(300, 300))
        self.btn_ac_analysis.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_ac_analysis.setFont(font)
        self.btn_ac_analysis.setAutoFillBackground(False)
        self.btn_ac_analysis.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"    border-style: flat;\n"
"    background: transparent;\n"
"}\n"
"QToolButton:hover{background-color: rgb(0, 170, 255)}\n"
"QToolButton:pressed{background-color: rgb(0, 85, 255)}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/figs/icon/分析.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ac_analysis.setIcon(icon)
        self.btn_ac_analysis.setIconSize(QtCore.QSize(100, 100))
        self.btn_ac_analysis.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_ac_analysis.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_ac_analysis.setObjectName("btn_ac_analysis")
        self.verticalLayout_4.addWidget(self.btn_ac_analysis)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.lab_name = QtWidgets.QLabel(self.base_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.lab_name.setFont(font)
        self.lab_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lab_name.setTextFormat(QtCore.Qt.PlainText)
        self.lab_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_name.setObjectName("lab_name")
        self.verticalLayout_2.addWidget(self.lab_name)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.btn_ac_train = QtWidgets.QToolButton(self.base_frame)
        self.btn_ac_train.setMinimumSize(QtCore.QSize(300, 300))
        self.btn_ac_train.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_ac_train.setFont(font)
        self.btn_ac_train.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"    border-style: flat;\n"
"    background: transparent;\n"
"}\n"
"QToolButton:hover{background-color: rgb(0, 170, 255)}\n"
"QToolButton:pressed{background-color: rgb(0, 85, 255)}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/figs/icon/跑步.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ac_train.setIcon(icon1)
        self.btn_ac_train.setIconSize(QtCore.QSize(100, 100))
        self.btn_ac_train.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_ac_train.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_ac_train.setObjectName("btn_ac_train")
        self.verticalLayout.addWidget(self.btn_ac_train)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(401, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.btn_back = QtWidgets.QPushButton(self.base_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setMinimumSize(QtCore.QSize(400, 100))
        self.btn_back.setMaximumSize(QtCore.QSize(800, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgba(50, 50, 50,0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{padding-bottom:8px}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/figs/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon2)
        self.btn_back.setIconSize(QtCore.QSize(45, 45))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.base_frame)

        self.retranslateUi(Std_Train_Select)
        QtCore.QMetaObject.connectSlotsByName(Std_Train_Select)

    def retranslateUi(self, Std_Train_Select):
        _translate = QtCore.QCoreApplication.translate
        Std_Train_Select.setWindowTitle(_translate("Std_Train_Select", "Form"))
        self.btn_ac_analysis.setText(_translate("Std_Train_Select", "动作分析"))
        self.lab_name.setText(_translate("Std_Train_Select", "擒敌拳"))
        self.btn_ac_train.setText(_translate("Std_Train_Select", "规范训练"))
        self.btn_back.setText(_translate("Std_Train_Select", "返回课程选择界面"))
import res_rc
